services:
  - type: web
    name: gas-utility-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gas_utility_service.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: gas-utility-service.onrender.com,*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: gas-utility-db
          property: connectionString

databases:
  - name: gas-utility-db
    databaseName: gas_utility_db
    user: gas_utility_user 