name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        # Render provides a deploy hook URL that you can use to trigger deployments
        # Add this URL as a secret in your GitHub repository settings 